jwt:
  secretKey: "my-very-long-and-secure-secret-key-for-mokoco-project-backend-service-2026"
  refreshKey: "39Mi/4xYqJuoNUvRVd+Nm8+SnjscMCOguulSpwmLJgA="
  access-expiration-ms: 1800000       # 30분
  refresh-expiration-ms: 604800000    # 7일

vworld:
  api-key: ${VWORLD_API_KEY}