server:
  port: 8082 # user-service가 8081을 쓰고 있으므로 포트 변경

spring:
  application:
    name: post-service # 서비스 이름 변경

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/post_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # DB명 구분 (post_db 등)
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: ./uploads/post-images # 이미지 파일이 저장되는 로컬 경로
  base-url: http://localhost:8082/images # 저장된 이미지에 접근하는 공개 URL