plugins {
    id 'java-library'
}

group = 'com.team2'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:3.4.2')
    api 'org.springframework:spring-web'
    implementation 'org.springframework:spring-context'
    implementation 'org.slf4j:slf4j-api'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor platform('org.springframework.boot:spring-boot-dependencies:3.4.2')
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
