CREATE TABLE payments (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 post_id BIGINT NOT NULL UNIQUE, portone_payment_id VARCHAR(255) NOT NULL UNIQUE,
 payer_email VARCHAR(255) NOT NULL, payee_email VARCHAR(255) NOT NULL,
 amount INTEGER NOT NULL, fee_amount INTEGER NOT NULL, net_amount INTEGER NOT NULL,
 status ENUM('COMPLETED','FAILED') NOT NULL,
 created_at DATETIME(6) NOT NULL, paid_at DATETIME(6), settled_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
