CREATE TABLE IF NOT EXISTS reports (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 target_type VARCHAR(20) NOT NULL,
 target_id BIGINT,
 target_email VARCHAR(100),
 reporter_email VARCHAR(100) NOT NULL,
 reason VARCHAR(20) NOT NULL,
 detail TEXT,
 status VARCHAR(20) NOT NULL,
 created_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
