server {
    listen 80;
    server_name 18.212.91.33 18.212.91.33.nip.io;

    # API 요청 및 소셜 로그인 인증 요청은 API Gateway로 라우팅
    location /api/ {
        proxy_pass http://api-gateway:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 기존 location /oauth2/ 를 아래처럼 변경
location /oauth2/authorization/ {
    proxy_pass http://mokoco-user-service:8081;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /login/oauth2/ {
    proxy_pass http://mokoco-user-service:8081;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}

    # 그 외 요청은 프론트엔드로 라우팅
    location / {
        proxy_pass http://frontend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}