CREATE TABLE regions (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 region_code VARCHAR(255), sido VARCHAR(255), sigungu VARCHAR(255), dong VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE users (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(100) NOT NULL,
 name VARCHAR(50) NOT NULL, nickname VARCHAR(50) NOT NULL UNIQUE,
 role ENUM('USER','ADMIN') NOT NULL, region_id BIGINT,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 CONSTRAINT fk_users_region FOREIGN KEY (region_id) REFERENCES regions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE refresh_token (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(255) NOT NULL UNIQUE, token VARCHAR(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE social_accounts (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL, provider ENUM('GOOGLE','KAKAO') NOT NULL,
 provider_id VARCHAR(255) NOT NULL,
 CONSTRAINT uk_social_provider UNIQUE (provider, provider_id),
 CONSTRAINT fk_social_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
