server:
  port: 8000 # 보통 게이트웨이가 앞단 대표 포트를 가집니다 (예: 8000번)

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081 # 또는 서비스 디스커버리 사용 시 lb://user-service
          predicates:
            - Path=/api/auth/**, /users/**

        - id: post-service
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**

        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**